
Name = "testnet2"

[[Metadata]]
Key = "network"
Value = "testnet2"

[API]

  [API.GRPC]
    Hosts = ["api.validators-testnet.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.validators-testnet.vega.xyz/query"]

  [API.REST]
    Hosts = ["https://api.validators-testnet.vega.xyz"]

[Apps]
  Console = "https://validator-testnet.console.vega.xyz/"
  Governance = "https://validator-testnet.governance.vega.xyz/"
  Explorer = "https://validator-testnet.explorer.vega.xyz/"
