
Name = "testnet2"

[[Metadata]]
Key = "network"
Value = "testnet2"

[API]

  [API.GRPC]
    Hosts = [
      "api-n00.validators-testnet.vega.rocks:3007",
      "api-n02.validators-testnet.vega.rocks:3007",
      "api-n03.validators-testnet.vega.rocks:3007",
      "api-n04.validators-testnet.vega.rocks:3007",
      "api-n05.validators-testnet.vega.rocks:3007",
    ]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api-validators-testnet.vega.rocks/graphql"]

  [API.REST]
    Hosts = ["https://api-validators-testnet.vega.rocks"]

[Apps]
  Console = "https://validator-testnet.console.vega.xyz/"
  Governance = "https://validator-testnet.governance.vega.xyz/"
  Explorer = "https://validator-testnet.explorer.vega.xyz/"
