log_level = 'info' # error, info, debug, trace, silent

[event_queue]
  # Use '0.0.0.0' to bind to all IPv4, '::' to bind to all IPv6 and IPv4
  healthcheck_iface = '127.0.0.1'
  # Remember to expose this port from Docker also
  healthcheck_port = 3001

  # Path to keep persistent state
  datadir = '/data'

  # Path to read secret key from. If this doesn't exist, one will be
  # written here on initial start and the public key written to the logs
  secretkey_path = '/secret.key'

[ethereum]
  # Example, replace before running
  http_endpoint = "https://ropsten.infura.io/v3/API_TOKEN"
  # Number of confirmations before forwarding an event
  confirmations = 50

  # Address and height at which to accept events from the ERC20Bridge contract
  [ethereum.erc20_bridge]
    # Use either the contract deployment height or `-1` for the current block
    # height at initial start
    start_height = -1
    address = "0x4149257d844Ef09f11b02f2e73CbDfaB4c911a73"

  # Addresses and height at which to accept events from the Staking contract
  [ethereum.staking]
    # Use either the contract deployment height or `-1` for the current block
    # height at initial start
    start_height = 12834524
    addresses = ["0x23d1bFE8fA50a167816fBD79D7932577c06011f4", "0x195064D33f09e0c42cF98E665D9506e0dC17de68"]

[vega]
  # Example, expose to the docker container and replace this
  grpc_endpoint = "127.0.0.1:3002"
