Name = "mainnet1"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = [
      "commodum.mainnet.vega.community:3007",
      "lovali.mainnet.vega.community:3007",
      "b-harvest.mainnet.vega.community:3007",
      "vega-data.nodes.guru:3007",
      "grpc.velvet.tm.p2p.org:443",
      "rockaway.mainnet.vega.community:3007",
      "greenfield-one.mainnet.vega.community:3007",
      "grpc.vega.xprv.io:443",
      "vega.mainnet.stakingcabin.com:3007"
    ]
    Retries = 5
  [API.REST]
    Hosts = [
      "http://commodum.mainnet.vega.community:3009",
      "http://lovali.mainnet.vega.community:3009",
      "http://b-harvest.mainnet.vega.community:3009",
      "http://vega-data.nodes.guru:3009",
      "https://rest.velvet.tm.p2p.org:443",
      "http://rockaway.mainnet.vega.community:3009",
      "http://greenfield-one.mainnet.vega.community:3009",
      "http://vega.xprv.io/datanode",
      "http://vega.mainnet.stakingcabin.com:3009"
    ]
  [API.GraphQL]
    Hosts = [
      "http://commodum.mainnet.vega.community:3008",
      "http://lovali.mainnet.vega.community:3008",
      "http://b-harvest.mainnet.vega.community:3008",
      "https://vega-data.nodes.guru:3008",
      "https://gql.velvet.tm.p2p.org:443/query",
      "http://rockaway.mainnet.vega.community:3008",
      "http://greenfield-one.mainnet.vega.community:3008",
      "https://vega.xprv.io/datanode/query",
      "https://vega.mainnet.stakingcabin.com/query"
    ]

[Console]
  URL = ""
  LocalPort = 1847

[TokenDApp]
  URL = "token.vega.xyz"
  LocalPort = 1848
