Name = "mainnet1"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = [
      "vega-mainnet-data-grpc.commodum.io:443",
      "lovali.mainnet.vega.community:3007",
      "b-harvest.mainnet.vega.community:3007",
      "nodes-guru.mainnet.vega.community:3007",
      "p2p.mainnet.vega.community:3007",
      "rockaway.mainnet.vega.community:3007",
      "greenfield-one.mainnet.vega.community:3007",
      "grpc.vega.xprv.io:443"
    ]
    Retries = 5
  [API.REST]
    Hosts = [
      "https://vega-mainnet-data-rest.commodum.io",
      "http://lovali.mainnet.vega.community:3009",
      "http://b-harvest.mainnet.vega.community:3009",
      "http://nodes-guru.mainnet.vega.community:3009",
      "http://p2p.mainnet.vega.community:3009",
      "http://rockaway.mainnet.vega.community:3009",
      "http://greenfield-one.mainnet.vega.community:3009",
      "http://vega.xprv.io/datanode"
    ]
  [API.GraphQL]
    Hosts = [
      "https://vega-mainnet-data-graphql.commodum.io/query",
      "http://lovali.mainnet.vega.community:3008",
      "http://b-harvest.mainnet.vega.community:3008",
      "http://nodes-guru.mainnet.vega.community:3008",
      "http://p2p.mainnet.vega.community:3008",
      "http://rockaway.mainnet.vega.community:3008",
      "http://greenfield-one.mainnet.vega.community:3008",
      "https://vega.xprv.io/datanode/query"
    ]

[Console]
  URL = ""
  LocalPort = 1847

[TokenDApp]
  URL = "token.vega.xyz"
  LocalPort = 1848
